// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVNOq9NQYpyq1JLv8f_KyIWv4eBvcHMos',
    appId: '1:206608718517:web:211a1122d03a0e4a847cfc',
    messagingSenderId: '206608718517',
    projectId: 'plant-doctor-1f44f',
    authDomain: 'plant-doctor-1f44f.firebaseapp.com',
    storageBucket: 'plant-doctor-1f44f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgApO54pvW2-9vq0MwF5Fi5cAncMqWDsE',
    appId: '1:206608718517:android:92af0be8c3b39ffc847cfc',
    messagingSenderId: '206608718517',
    projectId: 'plant-doctor-1f44f',
    storageBucket: 'plant-doctor-1f44f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdJwcHLvFAuywnnRo5N1eCeJNmC6H9zmg',
    appId: '1:206608718517:ios:f6f8d6a3680684aa847cfc',
    messagingSenderId: '206608718517',
    projectId: 'plant-doctor-1f44f',
    storageBucket: 'plant-doctor-1f44f.appspot.com',
    iosClientId: '206608718517-085n6psut9rv7q6i0tm25t3ir357qcmo.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterOnboarding',
  );
}
